# -*- coding: utf-8 -*-
"""Calculadora Básica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R60ltUVkk0j0CuRf58MJ79qJNN4eWIF3

# Calculadora Básica
"""

# Calculadora basica com python

# Nome do usuário
nome = input(' Digite o nome do usuário: ')

# Senha permitida
senha_permitida = '12345'

# Solicitação de senha
senha_usuario = input(' Digite a senha: ')

#Verificação de senha
if senha_usuario == senha_permitida:
  print(' Acesso permitido ')
else:
  print(' Senha incorreta. Acesso negado ')

# Lista
op = int(input(' 1. Soma\n 2. Subtração\n 3. Multiplicação\n 4. Divisão\n \nEscolha uma opção: '))

# Declarando as variáveis
num1 = int(input('Informe o primeiro valor: '))
num2 = int(input('Informe o segundo valor: '))

# Operações básicas
if op == 1:
  resultado = num1 + num2
  print('O resultado é:',resultado)
elif op == 2:
  resultado = num1 - num2
  print('O resultado é:', resultado)
elif op == 3:
  resultado = num1 * num2
  print('O resultado é', resultado)
elif op == 4:
  if num2 == 0:
    print('Divisão indefinida')
  resultado = num1 / num2
  resultado = round(resultado, 3)
  print(resultado)